name: another_task
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  
  # Bloc
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  equatable: ^2.0.5

  # UI
  firebase_ui_auth: ^1.16.0

  # Firebase & Cloud Services
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_analytics: ^11.3.3
  firebase_crashlytics: ^4.1.3
  google_mobile_ads: ^4.0.0
  shimmer: ^3.0.0
  onesignal_flutter: ^5.2.6

  # Utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0


flutter:
  uses-material-design: true
  fonts:
  - family: SocialIcons
    fonts:
      - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf